blank_issues_enabled: true
contact_links:
  - name: "💬 Обсуждения / Discussions"
    url: https://github.com/AlSokolov2/balance-daily/discussions
    about: "Для общих вопросов и общения. / For general questions and chatting."
